### PR TITLE
resolve some build errors

### PR DESCRIPTION
**Pull request by juniorohanyere**

### CODE REVIEW

**Comment by luxploit** [comment]
Hey there, thanks for the PR! Looks to be solid however, I'm a bit confused as to the additional kali_linux.md as it seems to be a carbon clone of the regular build doc but with lld and xorriso as extra listed dependencies, which are handled by the resolve_deps script and they should work on all debian based systems (ie. also Kali). You seem to have also changed line 28 of the doc, specifying the entire build path to ekernel.elf. Note that the kernel is copied to publish/skylight/boot/ once the build iso script is run, and the ability to directly run the kernel with no bootloader will be removed later.

**Comment by juniorohanyere** [comment]
Oh, my bad on line 28.

For the `lld` and the `xorriso`, they were not handled by the `resolve_deps` script. Then I thought it would be nice to have a documentation for specific operating systems

**Comment by luxploit** [comment]
resolve_deps installs lld-15 and xorriso, line 15:
```bash
elif [ -x "$(command -v apt)" ]; then
    sudo apt install -y nasm clang-15 lld-15 binutils python3 python3-pip qemu qemu-kvm grub2 xorriso
```

**Comment by juniorohanyere** [comment]
Fact is, the three packages I manually installed are grub2, lld and xorriso. I have no clue as to what went wrong. No error generated after running the script.

Well, in that case, the `kali_linux.md` is not necessary. I should delete that

**Comment by luxploit** [comment]
looks good, i'll pull this in now.

**Comment by juniorohanyere** [comment]
Great, thanks

**Pull request merged**
